authors = ["José Bayoán Santiago Calderón <naoyabpr@gmail.com>"]
license = "ISC"
repository = "https://github.com/Nosferican/NCEI.jl.git"
description = "Interface for the National Centers for Environmental Information (NCEI) API"
keywords = ["API", "Interface", "NOAA", "Weather", "Climate", "Data", "NCEI"]
name = "NCEI"
uuid = "1f554e9c-ddc6-5d78-a4ef-ff7defcf835d"
version = "1.0.3"
doi = "10.5281/zenodo.1210025"

[compat]
julia = "1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
LazyJSON = "fc18253b-5e1b-504c-a4a2-9ece4944c004"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
